
#registri calcolati
regs = {
    
    #GRUPPO:: dati generali
    4612000 : {
        'regs_main_hour' : 4611,
        'regs_main_minute' : 4610,
        'group' : 0,
        'plcaddr' : 'MW4610 MW4611',
        'tag' : 'HMI_ImpSetup_Conta_Ore_I  HMI_ImpSetup_Conta_Minuti_I',
        'descrizione' : 'Conta ore totale : ',
        'valuetype' : 'time'
    },

    4500001 : {
        'regs_main' : 4500,
        'group' : 0,
        'plcaddr' : 'MX9100.1',
        'tag' : 'HMI_Imp_Presenza_Allarmi_X ',
        'descrizione' : 'Presenza Allarmi',
        'valuetype' : 'bit',
        'bit' : 1,
        'valueDisplay' : "toggle_gray_green",
    },    
    4500005 : {
        'regs_main' : 4500,
        'group' : 0,
        'plcaddr' : 'MX9100.5',
        'tag' : 'HMI_Imp_Sel_Loc_Linea_Rem_X',
        'descrizione' : 'Selettore Locale Linea Remoto',
        'valuetype' : 'bit',
        'bit' : 5,
        'valueDisplay' : "toggle_gray_green",
    },    
    4500004 : {
        'regs_main' : 4500,
        'group' : 0,
        'plcaddr' : 'MX9100.4',
        'tag' : 'HMI_Imp_Stato_Avanz_X',
        'descrizione' : 'Avanzamento in Marcia',
        'valuetype' : 'bit',
        'bit' : 4,
        'valueDisplay' : "toggle_gray_green",
    },    


    20100005 : {
        'regs_main' : 20100,
        'group' : 0,
        'plcaddr' : 'MX20100.5',
        'tag' : 'MesData.xHmiCaricaDatiDn ',
        'descrizione' : 'Pulsante di start lavorazione',
        'valuetype' : 'bit',
        'bit' : 5,
        'valueDisplay' : "toggle_gray_green",
    },  
    20100002 : {
        'regs_main' : 20100,
        'group' : 0,
        'plcaddr' : 'MX20100.2',
        'tag' : 'MesData.xHmiEseguito',
        'descrizione' : 'Pulsante di stop lavorazione',
        'valuetype' : 'bit',
        'bit' : 2,
        'valueDisplay' : "toggle_gray_green",
    },  
    20100003 : {
        'regs_main' : 20100,
        'group' : 0,
        'plcaddr' : 'MX20100.3',
        'tag' : 'MesData.xHmiCaricaDati',
        'descrizione' : 'Lavorazione in corso',
        'valuetype' : 'bit',
        'bit' : 3,
        'valueDisplay' : "toggle_gray_green",
    },  
    20110000 : {
        'regs_main' : 20110,
        'regs_count' : 10,
        'group' : 0,
        'plcaddr' : 'MW20110',
        'tag' : 'MesData.sBarcodeRx',
        'descrizione' : 'Codice del prodotto in lavorazione',
        'valuetype' : 'char',
    },  


    8034000 : {
        'regs_main_hour' : 8034,
        'regs_main_minute' : 8033,
        'group' : 0,
        'plcaddr' : 'MW8034 MW8033',
        'tag' : 'I_Ore_Produzione  I_Minuti_Produzione',
        'descrizione' : 'Tempo manutenzione : ',
        'valuetype' : 'time'
    },

    #FINE GRUPPO

    #GRUPPO:: macchina
    4300005 : {
        'regs_main' : 4300,
        'group' : 1,
        'plcaddr' : 'MX8600.5',
        'tag' : 'Abl_Depress_X',
        'descrizione' : 'Abilitazione Depressore',
        'valuetype' : 'bit',
        'bit' : 5,
        'valueDisplay' : "toggle_gray_green",
    },  

    #FINE GRUPPO

    #GRUPPO:: Gr1 
    2500000 : {
        'regs_main' : 2500,
        'group' : 2,
        'plcaddr' : 'MX5000.0',
        'tag' : 'Gr1_Abl_Gruppo_X',
        'descrizione' : 'Abilitazione Gruppo 1',
        'valuetype' : 'bit',
        'bit' : 0,
        'valueDisplay' : "toggle_gray_green",
    },  
    2500004 : {
        'regs_main' : 2500,
        'group' : 2,
        'plcaddr' : 'MX5000.4',
        'tag' : 'Gr1_Abl_Gruppo_X',
        'descrizione' : 'Abilitazione StandBy',
        'valuetype' : 'bit',
        'bit' : 4,
        'valueDisplay' : "toggle_gray_green",
    },    
    #allarmi gruppo
    2526001 : {
        'regs_main' : 2526,
        'group' : 2,
        'plcaddr' : 'MD2176.1',
        'tag' : 'Gr1_Allarmi_W ',
        "testo" : "Termico Gruppo 1",
        "descrizione" : "Intervento della protezione magnetotermica dell'inverter / motore del gruppo di lavoro.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 1,
        'valueDisplay' : "toggle_gray_red",
    },
    2526002 : {
        'regs_main' : 2526,
        'group' : 2,
        'plcaddr' : 'MD2176.2',
        'tag' : 'Gr1_Allarmi_W ',
        "testo" : "Bloccaggio Nastro o Tens.Cinghia Gruppo 1",
        "descrizione" : "Il sistema automatico di bloccaggio del nastro abrasivo (se presente) è aperto.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 2,
        'valueDisplay' : "toggle_gray_red",
    },
    2526003 : {
        'regs_main' : 2526,
        'group' : 2,
        'plcaddr' : 'MD2176.3',
        "testo" : "Uscita Nastro Gruppo 1",
        "descrizione" : "Il nastro abrasivo è uscito lateralmente e deve essere rimesso in posizione. E' consigliabile verificare anche la pulizia delle fotocellule di centraggio del nastro.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 3,
        'valueDisplay' : "toggle_gray_red",
    },
    2526004 : {
        'regs_main' : 2526,
        'group' : 2,
        'plcaddr' : 'MD2176.4',
        "testo" : "Rottura Nastro Gruppo 2",
        "descrizione" : "Rottura del nastro abrasivo.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 4,
        'valueDisplay' : "toggle_gray_red",
    },
    2526007 : {
        'regs_main' : 2526,
        'group' : 2,
        'plcaddr' : 'MD2176.7',
        "testo" : "Anomalia Posizio. Gruppo 1",
        "descrizione" : "Anomalia del posizionamento del gruppo di lavoro (si veda quando indicato per l'anomalia del posizionamento del sollevamento).",
        "emergenza" : 0,
        'valuetype' : 'bit',
        'bit' : 7,
        'valueDisplay' : "toggle_gray_red",
    },
    2526008 : {
        'regs_main' : 2526,
        'group' : 2,
        'plcaddr' : 'MD2176.8',
        "testo" : "Error Nodo Gruppo 1",
        "descrizione" : "Presenza di un fault nel drive del motore o problemi di comunicazione con il drive (es. inverter della rotazione del motore operatore).",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 8,
        'valueDisplay' : "toggle_gray_red",
    },
    #FINE GRUPPO




    #GRUPPO:: Gr2 
    2600000 : {
        'regs_main' : 2600,
        'group' : 3,
        'plcaddr' : 'MX5200.0',
        'tag' : 'Gr2_Abl_Gruppo_X',
        'descrizione' : 'Abilitazione Gruppo 2',
        'valuetype' : 'bit',
        'bit' : 0,
        'valueDisplay' : "toggle_gray_green",
    },  
    2600004 : {
        'regs_main' : 2600,
        'group' : 3,
        'plcaddr' : 'MX5200.4',
        'tag' : 'Gr2_Abl_Gruppo_X',
        'descrizione' : 'Abilitazione StandBy',
        'valuetype' : 'bit',
        'bit' : 4,
        'valueDisplay' : "toggle_gray_green",
    },    
    #allarmi gruppo
    2626001 : {
        'regs_main' : 2626,
        'group' : 3,
        'plcaddr' : 'MW2626.1',
        'tag' : 'Gr2_Allarmi_W ',
        "testo" : "Termico Gruppo 2",
        "descrizione" : "Intervento della protezione magnetotermica dell'inverter / motore del gruppo di lavoro.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 1,
        'valueDisplay' : "toggle_gray_red",
    },
    2626002 : {
        'regs_main' : 2626,
        'group' : 3,
        'plcaddr' : 'MW2626.2',
        'tag' : 'Gr2_Allarmi_W ',
        "testo" : "Bloccaggio Nastro o Tens.Cinghia Gruppo 2",
        "descrizione" : "Il sistema automatico di bloccaggio del nastro abrasivo (se presente) è aperto.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 2,
        'valueDisplay' : "toggle_gray_red",
    },
    2626003 : {
        'regs_main' : 2626,
        'group' : 3,
        'plcaddr' : 'MW2626.3',
        "testo" : "Uscita Nastro Gruppo 2",
        "descrizione" : "Il nastro abrasivo è uscito lateralmente e deve essere rimesso in posizione. E' consigliabile verificare anche la pulizia delle fotocellule di centraggio del nastro.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 3,
        'valueDisplay' : "toggle_gray_red",
    },
    2626004 : {
        'regs_main' : 2626,
        'group' : 3,
        'plcaddr' : 'MW2626.4',
        "testo" : "Rottura Nastro Gruppo 2",
        "descrizione" : "Rottura del nastro abrasivo.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 4,
        'valueDisplay' : "toggle_gray_red",
    },
    2626007 : {
        'regs_main' : 2626,
        'group' : 3,
        'plcaddr' : 'MW2626.7',
        "testo" : "Anomalia Posizio. Gruppo 2",
        "descrizione" : "Anomalia del posizionamento del gruppo di lavoro (si veda quando indicato per l'anomalia del posizionamento del sollevamento).",
        "emergenza" : 0,
        'valuetype' : 'bit',
        'bit' : 7,
        'valueDisplay' : "toggle_gray_red",
    },
    2626008 : {
        'regs_main' : 2626,
        'group' : 3,
        'plcaddr' : 'MW2626.8',
        "testo" : "Error Nodo Gruppo 2",
        "descrizione" : "Presenza di un fault nel drive del motore o problemi di comunicazione con il drive (es. inverter della rotazione del motore operatore).",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 8,
        'valueDisplay' : "toggle_gray_red",
    },
    #FINE GRUPPO

    #GRUPPO:: Gr3 
    2700000 : {
        'regs_main' : 2700,
        'group' : 4,
        'plcaddr' : 'MX5400.0',
        'tag' : 'Gr3_Abl_Gruppo_X',
        'descrizione' : 'Abilitazione Gruppo 3',
        'valuetype' : 'bit',
        'bit' : 0,
        'valueDisplay' : "toggle_gray_green",
    },  
    2700004 : {
        'regs_main' : 2700,
        'group' : 4,
        'plcaddr' : 'MX5400.4',
        'tag' : 'Gr3_Abl_Gruppo_X',
        'descrizione' : 'Abilitazione StandBy',
        'valuetype' : 'bit',
        'bit' : 4,
        'valueDisplay' : "toggle_gray_green",
    },    
    #allarmi gruppo
    2726001 : {
        'regs_main' : 2726,
        'group' : 4,
        'plcaddr' : 'MW2726.1',
        'tag' : 'Gr3_Allarmi_W ',
        "testo" : "Termico Gruppo 3",
        "descrizione" : "Intervento della protezione magnetotermica dell'inverter / motore del gruppo di lavoro.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 1,
        'valueDisplay' : "toggle_gray_green",
    },
    2726002 : {
        'regs_main' : 2726,
        'group' : 4,
        'plcaddr' : 'MW2726.2',
        'tag' : 'Gr3_Allarmi_W ',
        "testo" : "Bloccaggio Nastro o Tens.Cinghia Gruppo 3",
        "descrizione" : "Il sistema automatico di bloccaggio del nastro abrasivo (se presente) è aperto.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 2,
        'valueDisplay' : "toggle_gray_red",
    },
    2726003 : {
        'regs_main' : 2726,
        'group' : 4,
        'plcaddr' : 'MW2726.3',
        "testo" : "Uscita Nastro Gruppo 3",
        "descrizione" : "Il nastro abrasivo è uscito lateralmente e deve essere rimesso in posizione. E' consigliabile verificare anche la pulizia delle fotocellule di centraggio del nastro.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 3,
        'valueDisplay' : "toggle_gray_red",
    },
    2726004 : {
        'regs_main' : 2726,
        'group' : 4,
        'plcaddr' : 'MW2726.4',
        "testo" : "Rottura Nastro Gruppo 3",
        "descrizione" : "Rottura del nastro abrasivo.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 4,
        'valueDisplay' : "toggle_gray_red",
    },
    2726007 : {
        'regs_main' : 2726,
        'group' : 4,
        'plcaddr' : 'MW2726.7',
        "testo" : "Anomalia Posizio. Gruppo 3",
        "descrizione" : "Anomalia del posizionamento del gruppo di lavoro (si veda quando indicato per l'anomalia del posizionamento del sollevamento).",
        "emergenza" : 0,
        'valuetype' : 'bit',
        'bit' : 7,
        'valueDisplay' : "toggle_gray_red",
    },
    2726008 : {
        'regs_main' : 2726,
        'group' : 4,
        'plcaddr' : 'MW2726.8',
        "testo" : "Error Nodo Gruppo 3",
        "descrizione" : "Presenza di un fault nel drive del motore o problemi di comunicazione con il drive (es. inverter della rotazione del motore operatore).",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 8,
        'valueDisplay' : "toggle_gray_red",
    },
    #FINE GRUPPO

    #allarmi
    4352000 : {
        'regs_main' : 4352,
        'group' : 5,
        'plcaddr' : 'MW4352.0',
        "testo" : "Mc Superiore Emergenza Generale",
        "descrizione" : "La macchina è in emergenza.L'emergenza può essere stata causata dall'attivazione di un pulsante a fungo oppure da un altro allarme macchina come la rottura di un nastro.",
        "emergenza" : 0,
        'valuetype' : 'bit',
        'bit' : 0,
        'valueDisplay' : "toggle_gray_red",
    },
    4352001 : {
        'regs_main' : 4352,
        'group' : 5,
        'plcaddr' : 'MW4352.1',
        "testo" : "Mc Superiore Termico Avanzamento",
        "descrizione" : "Intervento della protezione magnetotermica dell'inverter / motore del trasporto.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 1,
        'valueDisplay' : "toggle_gray_red",
    },
    4352002 : {
        'regs_main' : 4352,
        'group' : 5,
        'plcaddr' : 'MW4352.2',
        "testo" : "Mc Superiore Termico Depressore",
        "descrizione" : "Intervento della protezione magnetotermica dell'inverter / motore del depressore.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 2,
        'valueDisplay' : "toggle_gray_red",
    },
    4352003 : {
        'regs_main' : 4352,
        'group' : 5,
        'plcaddr' : 'MW4352.3',
        "testo" : "Mc Superiore Termico Spazzola 1",
        "descrizione" : "Intervento della protezione magnetotermica dell'inverter / motore della spazzola esterna 1.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 3,
        'valueDisplay' : "toggle_gray_red",
    },
    4352004 : {
        'regs_main' : 4352,
        'group' : 5,
        'plcaddr' : 'MW4352.4',
        "testo" : "Mc Superiore Termico Spazzola 2",
        "descrizione" : "Intervento della protezione magnetotermica dell'inverter / motore della spazzola esterna 2.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 4,
        'valueDisplay' : "toggle_gray_red",
    },
    4352005 : {
        'regs_main' : 4352,
        'group' : 5,
        'plcaddr' : 'MW4352.5',
        "testo" : "Mc Superiore Termico Sollevamento",
        "descrizione" : "Intervento della protezione magnetotermica dell'inverter / motore del sollevamento.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 5,
        'valueDisplay' : "toggle_gray_red",
    },
    4352006 : {
        'regs_main' : 4352,
        'group' : 5,
        'plcaddr' : 'MW4352.6',
        "testo" : "Allarme Mancanza Aria",
        "descrizione" : "La pressione dell'aria in entrata alla macchina è scesa al di sotto della soglia minima necessaria ad un corretto funzionamento della macchina.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 6,
        'valueDisplay' : "toggle_gray_red",
    },
    4352007 : {
        'regs_main' : 4352,
        'group' : 5,
        'plcaddr' : 'MW4352.7',
        "testo" : "Mc Superiore Porte Aperte ",
        "descrizione" : "Le porte a protezione dal contatto con in gruppi di lavoro sono aperte. La macchina rimane in emergenza e non può essere avviata.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 7,
        'valueDisplay' : "toggle_gray_red",
    },
    4352008 : {
        'regs_main' : 4352,
        'group' : 5,
        'plcaddr' : 'MW4352.8',
        "testo" : "Mc Superiore Uscita Tappeto",
        "descrizione" : "Il tappeto è sbandato lateralmente, andando ad attivare uno dei finecorsa posto su ciascun lato della macchina. Per evitare che il tappeto si danneggi, la macchina va in emergenza e non può essere avviata finché il finecorsa attivato non viene liberato e il tappeto rimesso nella sua propria sede.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 8,
        'valueDisplay' : "toggle_gray_red",
    },
    4353002 : {
        'regs_main' : 4353,
        'group' : 5,
        'plcaddr' : 'MW4353.2',
        "testo" : "Porte Aperte zona Mahros",
        "descrizione" : "Segnalazione dell’apertura dei cancelli della zona di carico",
        "emergenza" : 0,
        'valuetype' : 'bit',
        'bit' : 2,
        'valueDisplay' : "toggle_gray_red",
    },
    4353003 : {
        'regs_main' : 4353,
        'group' : 5,
        'plcaddr' : 'MW4353.3',
        "testo" : "Mc Superiore Eccesso Spessore",
        "descrizione" : "Qualora si presentasse in entrata alla macchina un pezzo avente uno spessore superiore a quello impostato, di una quantità potenzialmente pericolosa per l'integrità della macchina, si aziona un finecorsa che ferma il trasporto, disattivando anche la selezione del trasporto stesso nella pagina dei dispositivi ausiliari. Inoltre il sollevamento si apre automaticamente di una quantità sufficiente a permettere una agevole rimozione del pezzo.\
La macchina non va in emergenza né in stop.\
Il sollevamento si riporta automaticamente alla posizione impostata quando viene riabilitato il pulsante di selezione del trasporto.\
Se il pezzo che aveva causato l'eccesso spessore aveva già impegnato la macchina (presenza pezzo), prima di riposizionare la macchina a spessore, il trasporto si attiva e rimane in marcia fino a che il pezzo memoriazzato in entrata non viene evacuato in uscita.",
        "emergenza" : 0,
        'valuetype' : 'bit',
        'bit' : 3,
        'valueDisplay' : "toggle_gray_red",
    },
    4353005 : {
        'regs_main' : 4353,
        'group' : 5,
        'plcaddr' : 'MW4353.5',
        "testo" : "Mc Superiore Micro Apertura",
        "descrizione" : "La macchina è stata aperta fino al punto da attivare il finecorsa di limite superiore",
        "emergenza" : 0,
        'valuetype' : 'bit',
        'bit' : 5,
        'valueDisplay' : "toggle_gray_red",
    },
    4353006 : {
        'regs_main' : 4353,
        'group' : 5,
        'plcaddr' : 'MW4353.6',
        "testo" : "Mc Superiore Micro Chiusura",
        "descrizione" : "La macchina è stata aperta fino al punto da attivare il finecorsa di limite inferiore",
        "emergenza" : 0,
        'valuetype' : 'bit',
        'bit' : 6,
        'valueDisplay' : "toggle_gray_red",
    },
    4353007 : {
        'regs_main' : 4353,
        'group' : 5,
        'plcaddr' : 'MW4353.7',
        "testo" : "Mc Superiore Anomalia Pos. Soll.",
        "descrizione" : "Nel corso di un posizionamento dello spessore della macchina, è stata rilevata una anomalia.\
E' possibile che qualcosa abbia impedito al sollevamento di muoversi alla velocità prevista o che sia bloccato, ma l'evento più probabile che genera questo allarme è un posizionamento che si è concluso fuori dal valore di tolleranza stabilito. In questo caso è generalmente sufficiente ritoccare leggermente il parametro macchina che tiene conto dell'inerzia del sollevamento della macchina in fase di arresto del posizionamento.",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 7,
        'valueDisplay' : "toggle_gray_red",
    },
    4353008 : {
        'regs_main' : 4353,
        'group' : 5,
        'plcaddr' : 'MW4353.8',
        "testo" : "Mc Superiore Error Nodo",
        "descrizione" : "Problemi di comunicazione del/i drive della macchina (es. inverter trasporto).",
        "emergenza" : 1,
        'valuetype' : 'bit',
        'bit' : 8,
        'valueDisplay' : "toggle_gray_red",
    },

}